#spring.application.name=ftc-mongo

# WAS
server:
  port: 8081
  servlet:
    application-display-name: Bandisnc FTC Mongo DB Web Server
    session:
      timeout: 7200
      cookie:
        name:


spring:
  data:
    mongodb:
#      uri: mongodb://testuser:testuser01!@localhost:27017/?authSource=test
      host: 192.168.11.7
      port: 27017
      authentication-database: test
      username: testuser
      password: testuser01!


